export const enum SocketActions {
  CREATE_ROOM = 'CREATE_ROOM',
  CONNECT_ROOM = 'CONNECT_ROOM',
  EXIST_ROOM = 'EXIST_ROOM',
  FULL_ROOM = 'FOOL_ROOM',
  ENTER_ROOM = 'ENTER_ROOM',
  NOT_FOUND_ROOM = 'NOT_FOUND_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  ADD_PEER = 'ADD_PEER',
  SEND_SDP = 'SEND_SDP', //'RELAY_SDP'
  SET_DESCRIPTION = 'SET_DESCRIPTION', //'SESSION_DESCRIPTION'
  SEND_ICE = 'SEND_ICE', //'RELAY_ICE'
  SET_ICE = 'SET_ICE', //'ICE_CANDIDATE'
  REMOVE_PEER = 'REMOVE_PEER',
  LEAVE_ROOM = 'LEAVE_ROOM',
  SEND_MESSAGE = 'SEND_MESSAGE',
}

export const CONFIG = {
  iceServers: [{ urls: ['stun:stun.l.google.com:19302'] }],
};
